#ifndef LR2_DBCOMMAND_H
#define LR2_DBCOMMAND_H

const char *TEMPLATE_SQL = "CREATE TABLE IF NOT EXISTS foo(a,b,c); INSERT INTO FOO VALUES(1,2,3); INSERT INTO FOO SELECT * FROM FOO;";

#endif //LR2_DBCOMMAND_H
